apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: we-cluster1
spec:
  address: 1.2.3.4
  labels:
    app: we-cluster1
---
apiVersion: v1
kind: Service
metadata:
  name: we-cluster1
spec:
  ports:
  - port: 8080
  selector:
    app: we-cluster1
